version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  api:
    container_name: ntk-api
    restart: unless-stopped
    image: ntk-api-prod:1.0.0
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      DATABASE_USER: user123
      DATABASE_PASSWORD: password123
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE: db123
      API_URL: api
      PORT: 8000
  client:
    container_name: ntk-client
    restart: unless-stopped
    image: ntk-client-prod:1.0.0
    build:
      context: client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${API_URL}
        REACT_APP_API_PORT: ${API_PORT}
    ports:
      - 80:3000
    depends_on:
      - api