version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  api:
    container_name: ntk-api
    restart: unless-stopped
    image: ntk-api-prod:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres